site_name: Single Source Tutorial 

# Repository
repo_url: https://github.com/freesig/test_rendy

nav:
  - Triangle Tutorial: tri_tutorial.md

# Theme
theme:
  name: 'material'
  feature:
    tabs: true
  font:
    text: 'Work Sans'
    code: 'Roboto Mono'
  palette:
    primary: 'indigo'
    accent: 'indigo'

# Extensions
markdown_extensions:
  - admonition
  - meta
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.tilde
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.extra
  - pymdownx.betterem
